---
- name: Install and configure toolbox
  hosts: localhost
  connection: local
  gather_facts: false

  pre_tasks:
    - name: Install collections
      community.general.ansible_galaxy_install:
        type: both
        requirements_file: "requirements.yml"

  roles:
    - role: toolbox_packages
