---
- name: Install and configure toolbox
  hosts: localhost
  connection: local
  gather_facts: true

  pre_tasks:
    - name: Create the `aur_builder` user
      become: true
      ansible.builtin.user:
        name: aur_builder
        create_home: true
        group: wheel
    - name: Allow the `aur_builder` user to run `sudo pacman` without a password
      become: true
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/11-install-aur_builder
        line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
        create: true
        mode: "0644"
        validate: "visudo -cf %s"
    - name: Install collections
      community.general.ansible_galaxy_install:
        type: both
        requirements_file: "requirements.yml"

  tasks:
    - name: Install paru
      kewlfft.aur.aur:
        name: paru
      become: true
      become_user: aur_builder
    - name: Install toolbox tools
      register: toolbox_result
      ansible.builtin.shell: "toolbox run paru -y --skipreview --needed -S $(cat {{ playbook_dir }}/packages.txt)"
      changed_when: "'nothing' not in toolbox_result.stdout"
      failed_when: false
