# :vim: set ft=yaml.ansible:
---
- name: Configure user (run as root)
  hosts: localhost
  connection: local
  tags: root
  vars_prompt:
    - name: user_password
      prompt: Enter the user's password

  roles:
    - create_user

- name: Install and configure base system
  hosts: localhost
  connection: local
  gather_facts: true

  pre_tasks:
    - name: Install collections
      community.general.ansible_galaxy_install:
        type: both
        requirements_file: "requirements.yml"

  roles:
    - setup_aur
    - get_font_maple_mono
    - get_font_sf_pro
    - get_font_apple_emoji
    - setup_toolbox
    - setup_userscripts
    - setup_rbw
    # - setup_newsboat
    - setup_neomutt
