# :vim: set ft=yaml.ansible:
---
- name: Install and configure base system
  hosts: localhost
  connection: local
  gather_facts: true
  vars_prompt:
    - name: user_password
      prompt: Enter the user's password

  pre_tasks:
    - name: Install collections
      community.general.ansible_galaxy_install:
        type: both
        requirements_file: "requirements.yml"

  roles:
    - create_user
    - aur
    - setup_toolbox
