---
- name: Ensure rbw directory exists
  tags: rbw
  ansible.builtin.file:
    path: "~/.config/rbw"
    state: directory
    mode: "0755"

- name: Make config
  tags: rbw
  ansible.builtin.template:
    src: "rbw.json.j2"
    dest: "~/.config/rbw/config.json"
    mode: "0644"
