---
- name: Ensure sxhkd directory exists
  tags: sxhkd
  ansible.builtin.file:
    path: "~/.config/sxhkd"
    state: directory
    mode: "0755"

- name: Template config
  tags: sxhkd
  ansible.builtin.template:
    src: "sxhkdrc.j2"
    dest: "~/.config/sxhkd/sxhkdrc"
    mode: "0644"
