---
- name: Ensure font directory exists
  tags: fonts
  ansible.builtin.file:
    path: "{{ font_sf_pro_font_path }}/src"
    state: directory
    mode: "0755"

- name: Download and unzip
  tags: fonts
  ansible.builtin.unarchive:
    src: "https://devimages-cdn.apple.com/design/resources/download/SF-Pro.dmg"
    dest: "{{ font_sf_pro_font_path }}/src"
    remote_src: true

- name: Unzip DMG file
  tags: fonts
  ansible.builtin.unarchive:
    src: "{{ font_sf_pro_font_path }}/src/SF-Pro.dmg"
    dest: "{{ font_sf_pro_font_path }}/src"

- name: Unzip Payload
  tags: fonts
  ansible.builtin.unarchive:
    src: "{{ font_sf_pro_font_path }}/src/SFProFonts/Payload~"
    dest: "{{ font_sf_pro_font_path }}/src"

- name: Copy fonts
  tags: fonts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ font_sf_pro_font_path }}"
    mode: "0644"
  with_fileglob:
    - "{{ font_sf_pro_font_path }}/src/SFProFonts/Library/Fonts/*.otf"
