---
- name: Install and update packages
  tags: toolbox
  when: toolbox_packages[toolbox_toolbox_name | string] | length > 0
  register: toolbox_result
  failed_when: false
  changed_when: "'nothing' not in toolbox_result.stdout"
  ansible.builtin.command: "toolbox run -c {{ toolbox_toolbox_name }} sudo pacman --noconfirm -Sy --needed {{ item }}"
  with_items: "{{ toolbox_packages[toolbox_toolbox_name | string] }}"
