---
- name: Add to subuid and subgid for toolbox
  when: toolboxes is defined and toolboxes | length > 0
  tags: toolbox
  become: true
  block:
    - name: Subuid
      changed_when: false
      ansible.builtin.command: "usermod --add-subuids 10000-65536 {{ base_user }}"
    - name: Subgid
      changed_when: false
      ansible.builtin.command: "usermod --add-subgids 10000-65536 {{ base_user }}"

- name: Install toolbox
  when: toolboxes is defined and toolboxes | length > 0
  become: true
  tags: toolbox
  ansible.builtin.package:
    name: toolbox
    state: present

- name: Create toolboxes
  when: toolboxes is defined and toolboxes | length > 0
  tags: toolbox
  register: toolbox_result
  ansible.builtin.command: "toolbox create -y {{ item }}"
  changed_when: "'exists' not in toolbox_result.stderr"
  failed_when: false
  with_items: "{{ toolboxes }}"

- name: Install and update packages inside toolboxes
  tags: toolbox
  when: toolboxes is defined and toolboxes | length > 0
  ansible.builtin.include_tasks: install_toolbox_packages.yml
  vars:
    toolbox_toolbox_name: "{{ item2 }}"
  loop: "{{ toolboxes | flatten }}"
  loop_control:
    loop_var: "item2"
