---
- name: Install trizen
  kewlfft.aur.aur:
    name: "trizen"
    state: latest
  become_user: aur_builder
- name: Install packages inside toolbox
  kewlfft.aur.aur:
    name: "{{ packages }}"
    state: latest
  become_user: aur_builder
  vars:
    packages: "{{ lookup('file', 'packages_' + toolbox + '.txt').splitlines() }}"
