---
- name: Ensure khal directory exists
  tags: khal
  ansible.builtin.file:
    path: "~/.config/khal"
    state: directory
    mode: "0755"

- name: Template config
  tags: khal
  ansible.builtin.template:
    src: "config.j2"
    dest: "~/.config/khal/config"
    mode: "0644"
