---
- name: Ensure vdirsyncer directory exists
  tags: vdirsyncer
  ansible.builtin.file:
    path: "~/.config/vdirsyncer"
    state: directory
    mode: "0755"

- name: Template config
  tags: vdirsyncer
  ansible.builtin.template:
    src: "config.j2"
    dest: "~/.config/vdirsyncer/config"
    mode: "0644"
