---
- name: Add to subuid and subgid for toolbox
  when: toolboxes is defined and toolboxes | length > 0
  tags: toolbox
  become: true
  block:
    - name: Subuid
      changed_when: false
      ansible.builtin.command: "usermod --add-subuids 10000-65536 {{ base_user }}"
    - name: Subgid
      changed_when: false
      ansible.builtin.command: "usermod --add-subgids 10000-65536 {{ base_user }}"

- name: Install toolbox
  when: toolboxes is defined and toolboxes | length > 0
  become: true
  tags: toolbox
  ansible.builtin.package:
    name: toolbox
    state: present

- name: Create toolboxes
  when: toolboxes is defined and toolboxes | length > 0
  tags: toolbox
  register: toolbox_result
  ansible.builtin.command: "toolbox create -y {{ item }}"
  changed_when: "'exists' not in toolbox_result.stderr"
  failed_when: false
  with_items: "{{ toolboxes }}"

- name: Install ansible inside toolboxes
  register: toolbox_result
  tags: toolbox
  when: toolboxes is defined and toolboxes | length > 0
  ansible.builtin.command: "toolbox run -c {{ item }} sudo pacman --needed --noconfirm -S ansible"
  changed_when: "'nothing' not in toolbox_result.stdout"
  failed_when: false
  with_items: "{{ toolboxes }}"
